services:
  - type: web
    name: note-app
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      # Supabase Database
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_KEY
        sync: false
      # Firebase Admin (Backend)
      - key: FIREBASE_SERVICE_ACCOUNT
        sync: false
      # Firebase Authentication (Frontend) - Only 3 required for Auth
      - key: FIREBASE_API_KEY
        sync: false
      - key: FIREBASE_AUTH_DOMAIN
        sync: false
      - key: FIREBASE_PROJECT_ID
        sync: false

