services:
  - type: web
    name: note-app
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_KEY
        sync: false
      - key: FIREBASE_SERVICE_ACCOUNT
        sync: false

